version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: radiox-backend
    restart: always
    ports:
      - "8080:8080"
    environment:
      - SPOTIPY_CLIENT_ID=89c7e2957a7e465a8eeb9d2476a82a2d
      - SPOTIPY_CLIENT_SECRET=f8dc109892b9464ab44fba3b2502a7eb
      - SPOTIPY_REDIRECT_URI=http://127.0.0.1:8888/callback
      - SPOTIFY_PLAYLIST_ID=5i13fDRDoW0gu60f74cysp
      - RADIOX_STATION_NAME=radiox
    depends_on:
      - frontend

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: radiox-frontend
    restart: always
    ports:
      - "80:80" 